import { Product } from "@app/_models";

export const data_products: Product[] = [
  {
      "id": 1,
      "title": "Kendrick Lamar - good kid, m.A.A.d city",
      "price": 30.95,
      "description": "Año 2012. Incluye 3 temas extra. Uno de los mejores discos de Hip Hop que se han publicado en la última década. Disco 1 1.  SHERANE A.K.A. MASTER SPLINTER'S DA 2.  BITCH, DON'T KILL MY WIFE 3.  BACKSEAT FREESTYLE 4.  THE ART OF PEER PRESSURE 5.  MONEY TREES 6.  POETIC JUSTICE 7.  GOOD KID 8.  M.A.A.D CITY Disco 2 1.  SWIMMING POOLS (DRANK) 2.  SING ABOUT ME, I'M DYING OF THIRST 3.  REAL 4.  COMPTON 5.  THE RECIPE 6.  BLACK BOY FLY 7.  NOW OR NEVER",
      "category": "Hip-Hop",
      "image": "https://www.discosmarcapasos.com/media/img/covers/e86da0b88de99c5ea25127f875cafdcc521c650e-350.jpg",
  },
  {
    "id": 2,
    "title": "Kendrick Lamar - Damn.",
    "price": 35.05,
    "description": "El mejor MC de su generación (y eso es algo que hasta Bowie reconoció) se sumerge más profundamente en su propia mente y el resultado vuelve a ser sobresaliente. Una obra saturada de furia y pasión, caos y corazón que destila alma de soul y poso psicodélico. DAMM. puede resultar más accesible que el tremebundo, inmortal e incomparable To Pimp a Butterfly, pero es sin duda condenadamente adictivo y estremecedor. Puro conflicto, puro flow, pura clase. Colaboraciones para todos los gustos y palos, desde James Blake a Rihanna, pasando por BADBADNOTGOOD, Zacari y hasta U2, todos, quedan ensombrecidos por la presencia y forma del de Compton. Kendrick Lamar parece no tener techo y desde luego, hoy día, no tiene rival. DAMM. maldita sea. No te pierdas la brutal nueva obra del artista más en forma del panorama internacional.",
    "category": "Hip-Hop",
    "image": "https://www.discosmarcapasos.com/media/img/covers/70c1c87b9613738d6b4655c84a0ee554065c7360-350.jpg",
  },
  {
    "id": 3,
    "title": "King Gizzard and the Lizard Wizard - Nonagon Infinity",
    "price": 19.95,
    "description": "Los australianos se están ganando a pulso el sobrenombre de banda más currante del rock'n'roll actual con la publicación de su cuarto álbum en menos de año y medio. Tras el flirteo con el jazz cósmico bañado en psicodelia de “Quarters” y la brisa acústica y pastoral de “Paper Mache Dream Balloon”, “Nonagon Infinity” vuelve al frenesí salvaje de doble bombo y distorsión de su debut para Heavenly, “I’m In Your Mind Fuzz”. Lo que se dice un cierre de círculo con las guitarras en alto.",
    "category": "Punk",
    "image": "https://www.discosmarcapasos.com/media/img/covers/c90d59a04d1aaaa692bcaad2e2f97850ad8d002b-350.jpg",
  },
  {
    "id": 4,
    "title": "Aphex Twin - Selected Ambient Works 85-92",
    "price": 19.95,
    "description": "El álbum que dio a conocer a Aphex Twin, Selected Ambient Works 85-92, comienza con dos piezas musicales realmente sublimes, 'Xtal' y 'Tha', que no pueden faltar en tu colección, así como el álbum completo. Un clásico absoluto de la electrónica.",
    "category": "Electronica",
    "image": "https://www.discosmarcapasos.com/media/img/covers/ab99f80b461cff1a715463cc79e60cd7a93dbcf9-350.jpg",
  },
  {
    "id": 5,
    "title": "Nick Cave & the Bad Seeds - Push the Sky Away",
    "price": 35.95,
    "description": "Nuevo disco del Nick Cave más calmado y reflexivo que hayan visto estos ojos, un disco profundísimo, de mil escuchas, que revela un premio en cada rincón.",
    "category": "Pop-Rock",
    "image": "https://www.discosmarcapasos.com/media/img/covers/7fbbdd032655b1c9a9f8fa7786215df44c577a62-350.jpg",
  },
  {
    "id": 6,
    "title": "Tricky - Maxinquaye",
    "price": 19.95,
    "description": "Si quieres bailarla, adelante. Si quieres sentarte en una habitación a oscuras y dejar que te llene la cabeza de pensamientos extraños, también está bien. El debut de Tricky en 1995, Maxinquaye, es uno de esos álbumes que llevaron la música a la vanguardia, entrando en el número 2 de las listas británicas en el momento de su lanzamiento, a pesar de su escasa difusión, y acabando en los primeros puestos de muchas listas de fin de año. Pero a pesar de ser el precursor de uno de los estilos musicales más prevalentes de los noventa, existe al margen de las tendencias y del tiempo, y 20 años después sigue siendo una fuente de innovación musical",
    "category": "Funk/Trip-Hop",
    "image": "https://www.discosmarcapasos.com/media/img/covers/31f63db704c0d8264125f8da1ab27451af9004c6-350.jpg",
  },
  {
    "id": 7,
    "title": "Sonic Youth - Daydream Nation (Edición Remasterizada)",
    "price": 40.00,
    "description": "1988 Reedición 2014 Sexto álbum de Sonic Youth, su primer doble LP y el último para un sello independiente antes de firmar con Geffen. Considerado ampliamente como su momento decisivo, el álbum los catapultó a la corriente dominante y demostró que las bandas independientes podían disfrutar de un amplio éxito comercial sin comprometer su visión artística. Más recientemente, Daydream Nation ha sido reconocido como un clásico de su época: Pitchfork lo situó en el nº 1 de sus 100 mejores álbumes de los ochenta; Spin lo incluyó en el nº 13 de sus 125 mejores álbumes de 1985-2010; Rolling Stone lo situó en el nº 45 de su lista de 100 mejores álbumes de los ochenta y en el nº 328 de sus 500 mejores álbumes de todos los tiempos. Fue una de las 50 grabaciones elegidas por la Biblioteca del Congreso para ser añadidas al Registro Nacional de Grabaciones en 2006. Uno de los álbumes esenciales del Rock alternativo.",
    "category": "Pop-Rock",
    "image": "https://www.discosmarcapasos.com/media/img/covers/b9793a2dcaea27922af1b1e934136d8625e15e62-350.jpg",
  },
  {
    "id": 8,
    "title": "Yves Tumor - Praise a Lord Who Chews but Which Does Not Consume (Or Simply, Hot Between Worlds)",
    "price": 39.95,
    "description": "Yves Tumor publica su álbum más logrado, abarcando un amplio espectro de rock, psicodelia y electrónica en una asombrosa recalibración y reinvención de la música pop. Esta es la declaración más íntima y personal de Yves Tumor hasta la fecha, un viaje espiritual de múltiples conceptos en el que la oscuridad se funde con la luz, el pop con la innovación, la cacofonía con la calma de una iglesia. Producido por Noah Goldstein (Frank Ocean, Rosalía, Drake, Rihanna, Bon Iver), mezclado por Alan Moulder (My Bloody Valentine, Nine Inch Nails) y con las colaboraciones de Chris Greatti (Yungblud, WILLOW), Yves Rothman (Girlpool, Amaarae) y Rhys Hastings. Este quinto álbum de Sean Bowie (aka Yves Tumor), ¡de kilométrico título!, lo consagra como uno de los músicos más sorprendentes e innovadores del último lustro.",
    "category": "Pop-Rock",
    "image": "https://www.discosmarcapasos.com/media/img/covers/4d68999d4bda7bd78c6cec01a8cb898902d83652-350.jpg",
  },
  {
    "id": 9,
    "title": "Perro Mojado - Crónica del Espanto",
    "price": 10.00,
    "description": "Perro Mojado publica su segundo álbum Crónica Del Espanto. Con este disco Perro Mojado consolida su particular y truculento imaginario con un nuevo álbum repleto de ritmos repetitivos y arreglos guitarreros. El blues y el punk pasado por su desasosegante crisol. La banda granadina publica su segundo álbum Crónica del Espanto (Clifford 115-LP), cuya grabación, mezcla y mástering se lleva a cabo en abril de 2017 -por Carlos Díaz en los Estudios Producciones Peligrosas-, que verá la luz en vinilo, como firme apuesta de Clifford Records. En este segundo LP, la banda evidencia una propuesta cada vez más oscura y agresiva, con unos textos más cuidados, donde los desarrollos instrumentales cobran especial relevancia",
    "category": "Punk",
    "image": "https://www.discosmarcapasos.com/media/img/covers/a01b61efacced45d3cde44a5ce380b2dfd2583cf-350.jpg",
  },
  {
    "id": 10,
    "title": "Funkadelic - Maggot Brain",
    "price": 20.15,
    "description": "Cuenta la leyenda que George Clinton le dijo a su guitarrista Eddie Hazel cuando se encerraron para grabar la pieza que da título al 3er trabajo de Funkadelic, una elegía por el planeta Tierra, algo así: toca como si tu madre acabase de morir. El resultado fue un temazo claramente influenciado por Hendrix, una composición enorme más allá del bien y del mal, de más de 10 minutos donde la guitarra llora puro sentimiento, donde la guitarra vibra produciendo una seducción irrechazable. Incluye también dos sencillos con el habitual humor irónico que alcanzaron el Top 50: 'You And Your Folks, Me And My Folks' y 'Can You Get To My Folks'. El collage sonoro de 9 minutos Wars Of Armageddon. Todo el álbum posee una atmósfera y un alma únicas, funk torrencial, energía, emoción y sensualidad a raudales. ¡Arrebatador! Uno de esos clásicos imprescindibles que merecen el calificativo de mágicos.",
    "category": "Funk/Trip-Hop",
    "image": "https://www.discosmarcapasos.com/media/img/covers/db8318b777f5ed850677f36bb0d79c8b66d9952d-350.jpg",
  },
  {
    "id": 11,
    "title": "Tyler, The Creator - Igor",
    "price": 39.95,
    "description": "De lo bueno lo mejor, de lo mejor, lo superior.",
    "category": "Hip-Hop",
    "image": "https://www.discosmarcapasos.com/media/img/covers/4da802f0e7499033ea57258f9e2fbd39b629f52b-350.jpg",
  },
  {
    "id": 12,
    "title": "Moderat - III",
    "price": 20.95,
    "description": "Alegría para el cuerpo.",
    "category": "Electronica",
    "image": "https://www.discosmarcapasos.com/media/img/covers/84bd17dd760c50b44ec8728414fa071650148252-350.jpg",
  }
]
